version: "3.8"

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://cache
      - JWT_SECRET=jhjdncjbhnjs

    depends_on:
      - redis

    expose:
      - 5000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - VITE_SERVER_URL=http://server:5000
    depends_on:
      - server
    expose:
      - 8080
